name: "PR Description Validator"
description: "Ensures PR descriptions follow standardized templates with proper checkboxes, semantic commits, issue references, and labels"
author: "PR Validator Team"

inputs:
  config_file:
    description: "Path to configuration file (supports .md files with frontmatter or direct .yml/.yaml config files)"
    required: false
    default: ".github/PULL_REQUEST_TEMPLATE.md"
  config_branch:
    description: "Branch to fetch the configuration file from. If not specified, uses the current branch."
    required: false
    default: ""
  fail_on_error:
    description: "Whether to fail the workflow if validation fails"
    required: false
    default: "true"
  github_token:
    description: "GitHub token for API access"
    required: false

outputs:
  validation-result:
    description: "Result of validation (passed/failed)"
  validation-errors:
    description: "List of validation errors found"

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "check-square"
  color: "green"
