name: PR Template Validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-config-yaml
  cancel-in-progress: true

jobs:
  validate-template:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Validate PR Template
        uses: jcantosz/action-check-pr-description@main
        with:
          config_file: .github/pr-validation-config.yml
          fail_on_error: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_branch: main
      - name: Comment validation result on PR
        run: |
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "Validation result: ${{ steps.validate-template.outputs.validation-result }}\nErrors: ${{ steps.validate-template.outputs.validation-errors }}" \
            --repo ${{ github.repository }}
