name: PR Template Validation Fallback on Template

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate-template:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Validate PR Template
        uses: jcantosz/action-check-pr-description@main
        with:
          fail_on_error: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
