name: PR Template Validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, assigned, unassigned, review_requested, review_request_removed]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-config-yaml
  cancel-in-progress: true

jobs:
  validate-template:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Validate PR Template
        id: validate-template
        uses: jcantosz/action-check-pr-description@main
        with:
          config_file: .github/pr-validation-config.yml
          fail_on_error: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_branch: main

      - name: Comment validation result on PR
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATION_RESULT: ${{ steps.validate-template.outputs.validation-result }}
          VALIDATION_ERRORS: ${{ steps.validate-template.outputs.validation-errors }}
        run: |
          # Create a temporary file for the comment
          COMMENT_FILE=$(mktemp)
          
          # Write the header to the comment file
          if [ "$VALIDATION_RESULT" == "passed" ]; then
            echo "### ✅ PR Validation Result: PASSED" > "$COMMENT_FILE"
            echo "" >> "$COMMENT_FILE"
            echo "All validation checks have passed successfully!" >> "$COMMENT_FILE"
          else
            echo "### ❌ PR Validation Result: FAILED" > "$COMMENT_FILE"
            echo "" >> "$COMMENT_FILE"
            echo "**The following issues were found:**" >> "$COMMENT_FILE"
            echo "" >> "$COMMENT_FILE"
            
            # Replace \n with actual newlines and prefix each line with "- "
            echo "$VALIDATION_ERRORS" | sed 's/\\n/\n/g' | sed 's/^/- /' >> "$COMMENT_FILE"
          fi
          
          # Post the comment using the file content
          gh pr comment "${{ github.event.pull_request.number }}" --body-file "$COMMENT_FILE" --repo "${{ github.repository }}"
          
          # Clean up
          rm "$COMMENT_FILE"
